/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Approval } from "./Approval";
import { ApprovalCountArgs } from "./ApprovalCountArgs";
import { ApprovalFindManyArgs } from "./ApprovalFindManyArgs";
import { ApprovalFindUniqueArgs } from "./ApprovalFindUniqueArgs";
import { CreateApprovalArgs } from "./CreateApprovalArgs";
import { UpdateApprovalArgs } from "./UpdateApprovalArgs";
import { DeleteApprovalArgs } from "./DeleteApprovalArgs";
import { ApprovalService } from "../approval.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Approval)
export class ApprovalResolverBase {
  constructor(
    protected readonly service: ApprovalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "read",
    possession: "any",
  })
  async _approvalsMeta(
    @graphql.Args() args: ApprovalCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Approval])
  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "read",
    possession: "any",
  })
  async approvals(
    @graphql.Args() args: ApprovalFindManyArgs
  ): Promise<Approval[]> {
    return this.service.approvals(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Approval, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "read",
    possession: "own",
  })
  async approval(
    @graphql.Args() args: ApprovalFindUniqueArgs
  ): Promise<Approval | null> {
    const result = await this.service.approval(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Approval)
  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "create",
    possession: "any",
  })
  async createApproval(
    @graphql.Args() args: CreateApprovalArgs
  ): Promise<Approval> {
    return await this.service.createApproval({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Approval)
  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "update",
    possession: "any",
  })
  async updateApproval(
    @graphql.Args() args: UpdateApprovalArgs
  ): Promise<Approval | null> {
    try {
      return await this.service.updateApproval({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Approval)
  @nestAccessControl.UseRoles({
    resource: "Approval",
    action: "delete",
    possession: "any",
  })
  async deleteApproval(
    @graphql.Args() args: DeleteApprovalArgs
  ): Promise<Approval | null> {
    try {
      return await this.service.deleteApproval(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
