/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Process } from "./Process";
import { ProcessCountArgs } from "./ProcessCountArgs";
import { ProcessFindManyArgs } from "./ProcessFindManyArgs";
import { ProcessFindUniqueArgs } from "./ProcessFindUniqueArgs";
import { CreateProcessArgs } from "./CreateProcessArgs";
import { UpdateProcessArgs } from "./UpdateProcessArgs";
import { DeleteProcessArgs } from "./DeleteProcessArgs";
import { ProcessService } from "../process.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Process)
export class ProcessResolverBase {
  constructor(
    protected readonly service: ProcessService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Process",
    action: "read",
    possession: "any",
  })
  async _processesMeta(
    @graphql.Args() args: ProcessCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Process])
  @nestAccessControl.UseRoles({
    resource: "Process",
    action: "read",
    possession: "any",
  })
  async processes(
    @graphql.Args() args: ProcessFindManyArgs
  ): Promise<Process[]> {
    return this.service.processes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Process, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Process",
    action: "read",
    possession: "own",
  })
  async process(
    @graphql.Args() args: ProcessFindUniqueArgs
  ): Promise<Process | null> {
    const result = await this.service.process(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Process)
  @nestAccessControl.UseRoles({
    resource: "Process",
    action: "create",
    possession: "any",
  })
  async createProcess(
    @graphql.Args() args: CreateProcessArgs
  ): Promise<Process> {
    return await this.service.createProcess({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Process)
  @nestAccessControl.UseRoles({
    resource: "Process",
    action: "update",
    possession: "any",
  })
  async updateProcess(
    @graphql.Args() args: UpdateProcessArgs
  ): Promise<Process | null> {
    try {
      return await this.service.updateProcess({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Process)
  @nestAccessControl.UseRoles({
    resource: "Process",
    action: "delete",
    possession: "any",
  })
  async deleteProcess(
    @graphql.Args() args: DeleteProcessArgs
  ): Promise<Process | null> {
    try {
      return await this.service.deleteProcess(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
